apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mdf97bgnu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mdf97bgnu-go 
  name: mdf97bgnu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mdf97bgnu-go 
